name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
      - name: Install modules
      - run: yarn
      - name: Run tests
      - run: yarn test
      - run: echo "🍏 This job's status is ${{ job.status }}."
